### ISSUE TITLE
NOT WORKING UPDATE v1.0.3 -> 1.0.4

### ISSUE THREAD

**Issue by Litalino** [GBCLStudio/userip#10]
NOT WORKING UPDATE v1.0.3 -> 1.0.4

```
[root@instance public_html]# composer update gbcl/userip: "*"
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]?
Loading composer repositories with package information
Package "gbcl/userip:" listed for update is not locked.
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package fabpot/goutte is abandoned, you should avoid using it. Use symfony/browser-kit instead.
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating autoload files
256 packages you are using are looking for funding.
Use the composer fund command to find out more!
No security vulnerability advisories found.
```

**Comment by Litalino** [comment]
Problem 1
    - fof/geoip[0.1.0, ..., 0.1.7] require flarum/core ^0.1.0-beta.8 -> found flarum/core[v0.1.0-beta.8, ..., v0.1.0-beta.16] but it conflicts with your root composer.json require (^1.8).
    - fof/geoip[0.2.0, ..., 0.2.1] require flarum/core ^0.1.0-beta.14 -> found flarum/core[v0.1.0-beta.14, v0.1.0-beta.14.1, v0.1.0-beta.15, v0.1.0-beta.16] but it conflicts with your root composer.json require (^1.8).
    - fof/geoip 0.3.0 requires flarum/core ^0.1.0-beta.15 -> found flarum/core[v0.1.0-beta.15, v0.1.0-beta.16] but it conflicts with your root composer.json require (^1.8).
    - fof/geoip 0.4.0 requires flarum/core ^0.1.0-beta.16 -> found flarum/core[v0.1.0-beta.16] but it conflicts with your root composer.json require (^1.8).
    - gbcl/userip 1.0.4 conflicts with fof/geoip 1.3.0.
    - gbcl/userip 1.0.4 conflicts with fof/geoip 1.2.0.
    - gbcl/userip 1.0.4 conflicts with fof/geoip 1.0.1.
    - gbcl/userip 1.0.4 conflicts with fof/geoip 1.0.0.
    - gbcl/userip is locked to version 1.0.4 and an update of this package was not requested.
    - Root composer.json requires fof/geoip * -> satisfiable by fof/geoip[0.1.0, ..., 0.4.0, 1.0.0, ..., 1.3.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by Burial0268** [comment]
fof/geoip is now conflicts with this extension
