### ISSUE TITLE
很棒的插件，一点功能建议

### ISSUE THREAD

**Issue by DamonHu** [GBCLStudio/userip#3]
很不错的项目，填补了Flarum缺少记录ip的功能，非常棒的插件，针对我自己的使用体验，感觉也有可以提升的地方。
1. 当前后台仅支持显示IP属地信息，是否可以增加一列，展示ip信息的设置。可以开放给管理员查看。显示位置的话可以在帖子属地显示的右边，比如: Shanghai, CN | China Telecom     192.168.0.1
使用场景：某些垃圾机器人频繁发帖，如果管理员可以直接查看到发帖ip，就直接可以封禁该ip了，而不用再去数据库查询。
2. 我注意到查询服务器是代码中写死的`https://api.ip.sb/`，是否可以做成可配置项，在后台填写。这样有的用户就可以不需要修改代码，即可自己配置查询服务器，如果用户不配置，可以只记录ip，不去查询地址。这样既能避免查询服务器挂掉的风险，也可以记录ip

**Comment by DamonHu** [comment]
另外，我发送issue这一会就看到好几条ip记录，记录的ip是访问者的ip吗？如果是每个访问者的ip都记录的话，用户量一大，可能数据库记录的就太多垃圾数据了。并且每个ip查询都消耗性能，会造成体验的降低。

建议：用户发帖、回帖时才记录ip，因为这种场景用户会产生数据，这个数据才是网站管理员最关心的。至于谁访问的，其实对管理员来说意义不大

**Comment by Burial0268** [comment]
> 1. 当前后台仅支持显示IP属地信息，是否可以增加一列，展示ip信息的设置。可以开放给管理员查看。显示位置的话可以在帖子属地显示的右边，比如: Shanghai, CN | China Telecom     192.168.0.1

这一段的显示 Flarum 已经在 PostMeta 部分做了展示，点击用户发帖时间就可以看到了，也是默认管理员可见的，因此我觉得没有太大必要去做。

> 我注意到查询服务器是代码中写死的https://api.ip.sb/，是否可以做成可配置项

这一部分我已经在写相关配置了，还需要稍微等待一下（因为我人要中考）。前期如果有需求可以直接改 /src/Api/GeoIp.php 里面的设置

**Comment by Burial0268** [comment]
> 另外，我发送issue这一会就看到好几条ip记录，记录的ip是访问者的ip吗？如果是每个访问者的ip都记录的话，用户量一大，可能数据库记录的就太多垃圾数据了。并且每个ip查询都消耗性能，会造成体验的降低。
> 
> 建议：用户发帖、回帖时才记录ip，因为这种场景用户会产生数据，这个数据才是网站管理员最关心的。至于谁访问的，其实对管理员来说意义不大

这个其实不必要去担心，插件接了 Laravel 的 [Illuminate\Cache\Repository](https://github.com/GBCLStudio/userip/blob/main/src/Repositories/GeoIpRepository.php#L16) ，并且在 [这里](https://github.com/GBCLStudio/userip/blob/main/src/Repositories/GeoIpRepository.php#L88) 做了一个小小的判断，先检查是否存在已有数据库记录，不存在才会保存。并且保存到的 IP 也都是用户发帖，回帖时的 IP ，具体的 IP 信息可以去数据库的 `userip_info` 表里查看。

当然，如果您有更好的建议或者解决思路，也欢迎继续讨论。这里再次感谢您对插件提出的建议，谢谢
